name = "sha2"
description = "Secure Hash Algorithm 2 implemented in Ada"
version = "1.0.0"
website = "https://github.com/AntonMeep/sha2"
licenses = "ISC"
tags = ["cryptography", "security", "sha2"]

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]

[origin]
commit = "107d9c261e4b54b274a14bf1d675461227d3503b"
url = "git+https://github.com/AntonMeep/sha2.git"

