name = "pbkdf2"
description = "PBKDF2 implemented in Ada"
version = "1.0.0"
website = "https://github.com/AntonMeep/pbkdf2"
licenses = "ISC"
tags = ["cryptography", "security", "pbkdf2"]

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]

[origin]
commit = "548f5dc86a45119f82ae512fc27ad950e8b83b6b"
url = "git+https://github.com/AntonMeep/pbkdf2.git"

