name = "pbkdf2"
description = "PBKDF2 implemented in Ada"
version = "1.0.0"
website = "https://github.com/AntonMeep/pbkdf2"
licenses = "ISC"
tags = ["cryptography", "security", "pbkdf2"]

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]

[origin]
commit = "751e53be46861e0457180267372a75061b0d56cf"
url = "git+https://github.com/AntonMeep/pbkdf2.git"

